language: objective-c

osx_image: xcode9.0

cache:
- bundler
- cocoapods

before_install:
- bundle install
- bundle exec pod keys set ListioAPISecret $ListioAPISecret
- pod update
- pod install 

script:
- xcodebuild -version
- xcodebuild -workspace Listio.xcworkspace -scheme 'Hml' -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7"
- bash <(curl -s https://codecov.io/bash) -t 07101cd7-6101-475c-9b27-5426e067ac0c