language: objective-c

osx_image: xcode8.3

before_install:
    - pod install

script:
    - xcodebuild -workspace Listio.xcworkspace -scheme 'Listio' -sdk iphonesimulator clean build
    - xcodebuild test -workspace Listio.xcworkspace -scheme 'ListioTests' -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1'