language: objective-c

osx_image: xcode8.3

before_install:
    - pod install

script:
    travis_retry xcodebuild -workspace Listio.xcworkspace -scheme 'Listio' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1' clean build test