language: objective-c

osx_image: xcode8.3

before_install:
    - pod install

script:
  - cd Examples
  - xcodebuild -version
  - xcodebuild -workspace Listio.xcworkspace -scheme 'Listio' -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" -enableCodeCoverage YES test
  - bash <(curl -s https://codecov.io/bash) -t 07101cd7-6101-475c-9b27-5426e067ac0c