language: objective-c

osx_image: xcode8.3

cache:
- bundler
- cocoapods

before_install:
- bundle install
- bundle exec pod keys set ListioAPISecret $ListioAPISecret 
- rvm use system
- sudo gem install cocoapods
- pod repo update

script:
- xcodebuild -version
- xcodebuild -workspace Listio.xcworkspace -scheme 'Listio' -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7" -enableCodeCoverage YES test
- bash <(curl -s https://codecov.io/bash) -t 07101cd7-6101-475c-9b27-5426e067ac0c