language: objective-c

osx_image: xcode8.1

script:
    xcodebuild -workspace Listio.xcworkspace -scheme Listio -sdk iphonesimulator build
    xcodebuild test -workspace Listio.xcworkspace -scheme ListioTests -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1'